let Profiles = [
  {
    name: "Tipchan Songtheng",
    imageLink:
      "https://pbs.twimg.com/profile_images/1710009010873872384/Sohs7yX2_400x400.jpg",
    twitterLink: "https://twitter.com/tipchan_s",
    facebookLink: "",
    githubLink: "https://github.com/tsongtheng",
    linkedinLink: "https://www.linkedin.com/in/tipchan-songtheng-5417991a8/",
    instagramLink: "",
  },
  {
    name: "Chammoun Chakhap",
    imageLink: "https://avatars.githubusercontent.com/u/43007452?v=4",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/chammounc",
    linkedinLink: "https://www.linkedin.com/in/chammoun-chakhap-771093171",
    instagramLink: "",
  },
  {
    name: "Esin Ridollah",
    imageLink: "https://avatars.githubusercontent.com/u/86829637?v=4",
    twitterLink: "https://twitter.com/esinnation",
    facebookLink: "",
    githubLink: "https://github.com/esinnation",
    linkedinLink: "https://www.linkedin.com/in/esin-ridollah/",
    instagramLink: "https://www.instagram.com/esinnation/",
  },
  {
    name: "ISHAN AHMAD",
    imageLink: "",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/ishan-nahid",
    linkedinLink: "",
    instagramLink: "",
  },
  {
    name: "Aarushi Singh",
    imageLink: "https://avatars.githubusercontent.com/u/97330615?v=4",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/24-Aarushi-Singh-24",
    linkedinLink: "",
    instagramLink: "",
  },
  {
    name: "aecuto",
    imageLink: "",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/aecuto",
    linkedinLink: "",
    instagramLink: "",
  },
  {
    name: "Mayank-Creater",
    imageLink: "https://avatars.githubusercontent.com/u/67818466?v=4",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/Mayank-Creater",
    linkedinLink: "",
    instagramLink: "",
  },

  {
    name: "Jagpreet Singh Khurana",
    imageLink: "",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/Jagpreet153",
    linkedinLink: "",
    instagramLink: "",
  },
  {
    name: "Teeksha Harish",
    imageLink: "https://www.entoin.com/images/chara27.jpg",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/TeekshaHarish",
    linkedinLink: "",
    instagramLink: "",
  },
  {
    name: "Yash Doke",
    imageLink: "https://avatars.githubusercontent.com/u/140625127?v=4",
    twitterLink: "",
    facebookLink: "",
    githubLink: "https://github.com/22Yash",
    linkedinLink: "https://www.linkedin.com/in/yash-doke-232804271/",
    instagramLink: "",
  }, {
    name: "Prakash Patel",
    imageLink: "https://avatars.githubusercontent.com/u/41587867?v=4",
    twitterLink: "https://twitter.com/prakashp282",
    facebookLink: "",
    githubLink: "https://github.com/prakashp282",
    linkedinLink: "https://www.linkedin.com/in/prakashp282",
    instagramLink: "",
  }
];

export default Profiles;
